version: '3.8'

services:
postgress:
image: postgres:15
container_name: postgress_db
environment:
  POSTGRESS_USER: lamadev
  POSTGRESS_PASSWRORD: lama654321
  POSTGRESS_DB: school

ports:
    -'5432:5432⁠ '
volumes:
    - postgress_data:/var/lib/postgresql/data

app:
  container_name: nextjs_app
  ports:
  - '3000:3000'
  environment:
    - DATABASE_URL: "postgresql://lamadev:lama654321@localhost:5432/school"
  depends_on:
      -postgres


